### ISSUE TITLE
Tags URL is invalid, when baseURL = "/"

### ISSUE THREAD

**Issue by Vectorrent** [HelloRusk/HugoTeX#16]
I need to publish my site at multiple domains. To do this, I simply specify the following in my config.toml:
```
baseURL = "/"
```
This works great across my other sites, using other themes, and it mostly works in HugoTeX, as well.

However, tag URLs are invalid. When I click on the "games" tag, for example, I'm taken to the following URL:

https://tags/games/

Obviously, that doesn't work.

Anyway, this is a low priority issue, and not something that affects me much, at the moment. I just thought I'd let you know!

Thanks for creating such an awesome theme!

**Comment by kaisugi** [comment]
Thank you for pointing this out.
I have no idea how to solve this issue, but I would like to merge fix PR asap if you can create one, thanks!

**Comment by Vectorrent** [comment]
Just pushed a PR that addresses this issue. Not sure if it's a "good" fix, but it's worked for me, in the past.
