### ISSUE TITLE
Support of `lastmod`

### ISSUE THREAD

**Issue by catap** [HelloRusk/HugoTeX#22]
Hugo allows to define two dates on the page:
 - `date` when it was created and which is used for sorting;
 - `lastmod` when it was updated the last time.

Right now HugoTex shows `lastmod` if it availabe, which might be confused.

Maybe add `(Last time updated at ...)` ?

**Comment by kaisugi** [comment]
honestly I don't come up with a good idea because I don’t use this theme personally

If you have a good solution, feel free to send a PR (I guess you already added a new commint to the PR related to this issue

**Comment by catap** [comment]
I've added a draft commit by mistake to that PR O:-)

The best option that I have in mind is:

<img width="324" alt="Screenshot 2024-01-05 at 11 34 06" src="https://github.com/kaisugi/HugoTeX/assets/37775/edb0838c-acb5-4b16-95c1-8dfb6c660b56">

**Comment by catap** [comment]
After some thought I've decided to move with following format:

```diff
--- a/layouts/partials/postmeta.html
+++ b/layouts/partials/postmeta.html
@@ -1,5 +1,11 @@
 <span class="meta-post">
-  <i class="fa fa-calendar-alt"></i>{{ .Lastmod.Format ( .Site.Params.dateformat | default "Jan 2, 2006") }}
+  {{- $lastmod := .Lastmod.Format ( .Site.Params.dateformat | default "Jan 2, 2006") }}
+  {{- $pubdate := .PublishDate.Format ( .Site.Params.dateformat | default "Jan 2, 2006") }}
+  <i class="fa fa-calendar-alt"></i>
+  {{ $pubdate }}
+  {{- if ne $lastmod $pubdate }}
+  ({{ $lastmod }})
+  {{- end }}
   {{ if .Params.categories }}
     <br><i class="fa fa-folder-open"></i>
     {{ range .Params.categories }}
```

See example at https://kirill.korins.ky

I'll play with it for some time, and I satisfied I'll open PR.
