### ISSUE TITLE
Custom CSS?

### ISSUE THREAD

**Issue by ankush981** [HelloRusk/HugoTeX#4]
Hello, thanks a ton for the really amazing theme! I'm a newcomer to Hugo and so that might be the reason, but I can't figure out how to add my own CSS to this theme. Is it possible? Thanks in advance! 🙂

**Comment by kaisugi** [comment]
Hello, I guess the simplest way is to modify [/static/css/main.css](https://github.com/HelloRusk/HugoTeX/blob/master/static/css/main.css) file as you like.

Or you can adopt a new custom css by editing toml and html files like below.
https://mangolassi.it/topic/21569/how-do-i-use-custom-css-with-this-hugo-theme

**Comment by ankush981** [comment]
Ah, thanks a lot! Editing the main.css file works perfectly fine for me. 🙂
