### ISSUE TITLE
Add support for sidenotes

### ISSUE THREAD

**Issue by eeriksp** [HelloRusk/HugoTeX#5]
Latex.css provides a way to create sidenotes (see https://latex.vercel.app/#sidenotes).

Since the setup is somewhat complicated, I created a Hugo shortcode for that:

```html
{{ $id := md5 .Inner }}
<label for="{{ $id }}" class="sidenote-toggle sidenote-number"></label>
<input type="checkbox" id="{{ $id }}" class="sidenote-toggle" />
<span class="sidenote">{{ .Inner }}</span>
```

The first line uses the `md5` function to compute a unique `id` for the elements.

It can be used like this:

```
{% sidenote %}}
The content of the note.
{{% /sidenote %}}
```

In order for it to work, I had to include the Latex.css stylesheet in `layouts/partials/head.html` (`<link rel="stylesheet" href="https://latex.now.sh/style.css">`) since the stylesheet included as `static/latex.css` is ~200 lines shorter and does not include support for sidenotes.

I would propose merging this shortcode into this project as I believe that all of the users of the theme could benefit from it.
Also, perhaps `static/latex.css` could be updates to reflect the newest version of Latex.css?

**Comment by kaisugi** [comment]
Sounds nice.
Do you plan to send a PR?

**Comment by eeriksp** [comment]
Yes, sure!
Already working on it.

**Comment by kaisugi** [comment]
Thanks! I'm looking forward to it

**Comment by eeriksp** [comment]
The pull request is now ready: #6

**Comment by kaisugi** [comment]
Merged. Thank you for your contribution!
